#!/bin/bash

widthpercent=50

typeset -A contexts
contexts=$(kubectl config get-contexts -o name)

typeset -A menu
menu=(
)

for i in ${contexts[@]}; do
    menu+=( ["$i"]="kubectl config use-context ${i}" )
done

menu_nrows=${#menu[@]}

typeset -A colors
colors=(
    [-color-window]="#000000, #ffffff, #ffffff"
    [-color-normal]="#ffffff, #000000, #eee8d5, #272727, #ffffff"
    [-color-active]="#fdf6e3, #268bd2, #eee8d5, #268bd2, #fdf6e3"
    [-color-urgent]="#fdf6e3, #dc322f, #eee8d5, #dc322f, #fdf6e3"
)

# Window title
ROFI_TEXT="Kubernetes context"

# Optional window size
if [ -z ${widthpercent+x} ]; then
    ROFI_OPTIONS=(-location 0 -hide-scrollbar -bw 2)
else
    ROFI_OPTIONS=(-width $widthpercent -location 0 -hide-scrollbar -bw 2)
fi

# Optional window color
if ((${#colors[@]})); then
    for i in "${!colors[@]}"; do
        ROFI_COLORS+=($i "${colors[$i]}")
    done
else
    ROFI_COLORS=()
fi

launcher_options=(-dmenu -i -lines "${#menu[@]}" -p "${ROFI_TEXT}" \
         "${ROFI_COLORS[@]}" "${ROFI_OPTIONS[@]}")

launcher=(rofi "${launcher_options[@]}")

selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

if [[ -n $selection ]]
then
    exec ${menu[${selection}]}
fi

